// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhQBNEbJdlW3DCxcm12YRB6TA3nI0GrbA',
    appId: '1:298043532400:web:769c97d414375e60f000b5',
    messagingSenderId: '298043532400',
    projectId: 'quiz-app-3fa24',
    authDomain: 'quiz-app-3fa24.firebaseapp.com',
    storageBucket: 'quiz-app-3fa24.appspot.com',
    measurementId: 'G-4CWZCZ2Z5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvPmjQGjuv9w8S0mDJZai7jje_OZj0BNg',
    appId: '1:298043532400:android:f121cea959892f05f000b5',
    messagingSenderId: '298043532400',
    projectId: 'quiz-app-3fa24',
    storageBucket: 'quiz-app-3fa24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU8oPT_X5I6KCLMXefxCzvheQZftWwyqo',
    appId: '1:298043532400:ios:b51ff41f08f98a79f000b5',
    messagingSenderId: '298043532400',
    projectId: 'quiz-app-3fa24',
    storageBucket: 'quiz-app-3fa24.appspot.com',
    iosBundleId: 'com.example.appQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU8oPT_X5I6KCLMXefxCzvheQZftWwyqo',
    appId: '1:298043532400:ios:e5424a0ae8060c3ff000b5',
    messagingSenderId: '298043532400',
    projectId: 'quiz-app-3fa24',
    storageBucket: 'quiz-app-3fa24.appspot.com',
    iosBundleId: 'com.example.appQuiz.RunnerTests',
  );
}
